# -*- coding: utf-8 -*-
"""Pollenix-bjzoo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbI-QCJMNtXueRW2iHLhKvIAOf9SEN7Y
"""

from dataclasses import dataclass
import math
from datetime import datetime

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go


# ============================================================
# 京粉报 BJ Pollenix — 北京动物园 / 颐和园 双公园版
#
# 模型定位：
# 这是一个 literature-grounded experimental risk index，
# 不是临床诊断工具，也不是官方医学风险分级。
#
# 主要文献：
# 1) Zhou Y, Dai J, Liu H, Liu X. (2022)
#    Tourist risk assessment of pollen allergy in tourism attractions:
#    A case study in the Summer Palace, Beijing, China.
#    Frontiers in Public Health 10:1030066.
#    DOI: 10.3389/fpubh.2022.1030066
#
# 2) 北京动物园乔木数量来自：
#    《城市公园树木安全风险评估——以北京动物园为例》
#    DOI: 10.12171/j.1000-1522.20210200
#
# 本版本相较旧版：
# - 删除“公园面积 -> 蒿属/草本密度”的经验公式。
# - 删除证据较弱的 UV 与连续晴天模块。
# - 以 I_GZA / Green Zone Allergenicity Index 为植被危险度基础。
# - 使用文献中的木本花粉浓度 5 级阈值。
# - 风、温、湿、降雨、日照保留为动态气象修正层。
# - PM2.5 仅作为实验性炎症增强层。
# - 侧边栏可一键切换“北京动物园 / 颐和园”。
#
# 用户设定的有效绿地：
# - 北京动物园：40 ha
# - 颐和园：总面积 290.8 ha 的 40% = 116.32 ha
# ============================================================


@dataclass(frozen=True)
class AllergenicTree:
    chinese_name: str
    scientific_name: str
    count: int
    allergenic_potential: float   # AP
    pollen_emission: float        # PE
    flowering_duration: float     # FD, day
    crown_area: float             # S, m²
    canopy_height: float          # H, m
    parameter_note: str = ""


@dataclass(frozen=True)
class ParkProfile:
    name: str
    total_area_ha: float
    effective_green_area_ha: float
    trees: tuple
    data_note: str
    reliability_note: str


@dataclass
class ParkEnvironment:
    date: str

    pollen_density: float
    # 粒 / 1000 mm²
    # 与 Zhou et al. (2022) Table 1 的花粉浓度分级一致

    wind_speed: float
    # m/s

    humidity: float
    # %

    rainfall_48h: float
    # mm

    sunlight_hours: float
    # h

    temperature: float
    # °C

    pm25: float
    # μg/m³


# ============================================================
# 颐和园论文 Table 4 参数
# ============================================================

SUMMER_PALACE_TOTAL_AREA_HA = 290.8
SUMMER_PALACE_EFFECTIVE_GREEN_AREA_HA = (
    SUMMER_PALACE_TOTAL_AREA_HA * 0.40
)

SUMMER_PALACE_TREES = (
    AllergenicTree(
        "侧柏",
        "Platycladus orientalis",
        9446,
        3,
        3,
        21,
        13.72,
        9.6,
        "Zhou et al. (2022), Table 4",
    ),
    AllergenicTree(
        "圆柏",
        "Sabina chinensis / Juniperus chinensis",
        4062,
        3,
        3,
        16,
        15.20,
        10.1,
        "Zhou et al. (2022), Table 4",
    ),
    AllergenicTree(
        "垂柳",
        "Salix babylonica",
        3536,
        2,
        2,
        16,
        44.40,
        16.1,
        "Zhou et al. (2022), Table 4",
    ),
    AllergenicTree(
        "油松",
        "Pinus tabuliformis",
        3205,
        1,
        2,
        11,
        95.03,
        13.4,
        "Zhou et al. (2022), Table 4",
    ),
    AllergenicTree(
        "毛白杨",
        "Populus tomentosa",
        682,
        2,
        2,
        20,
        94.99,
        17.8,
        "Zhou et al. (2022), Table 4",
    ),
    AllergenicTree(
        "桑树",
        "Morus alba",
        196,
        2,
        1,
        20,
        67.02,
        14.2,
        "Zhou et al. (2022), Table 4",
    ),
    AllergenicTree(
        "白蜡",
        "Fraxinus chinensis",
        114,
        4,
        3,
        16,
        94.99,
        11.8,
        "Zhou et al. (2022), Table 4",
    ),
)


# ============================================================
# 北京动物园数据
#
# 乔木普查数量：
# 侧柏 325
# 圆柏 889
# 绦柳 317
# 油松 599
# 毛白杨 314
#
# 北京动物园没有公开与颐和园 Table 4 完全同维度的
# AP / PE / FD / crown area / canopy height 数据。
#
# 因此这里：
# - 同种植物直接使用颐和园 Table 4 参数作为 species-level proxy；
# - 绦柳 Salix matsudana 'Pendula' 暂以 Salix babylonica 参数代理。
#
# 这意味着动物园 I_GZA 是“代理估计”，不是原论文实测 I_GZA。
# ============================================================

BEIJING_ZOO_TOTAL_AREA_HA = 86.0
BEIJING_ZOO_EFFECTIVE_GREEN_AREA_HA = 40.0

BEIJING_ZOO_TREES = (
    AllergenicTree(
        "侧柏",
        "Platycladus orientalis",
        325,
        3,
        3,
        21,
        13.72,
        9.6,
        "数量来自北京动物园乔木普查；其余参数借用颐和园同种数据",
    ),
    AllergenicTree(
        "圆柏",
        "Juniperus chinensis",
        889,
        3,
        3,
        16,
        15.20,
        10.1,
        "数量来自北京动物园乔木普查；其余参数借用颐和园同种/同义种数据",
    ),
    AllergenicTree(
        "绦柳",
        "Salix matsudana 'Pendula'",
        317,
        2,
        2,
        16,
        44.40,
        16.1,
        "数量来自北京动物园乔木普查；AP/PE/FD/S/H 暂以 Salix babylonica 代理",
    ),
    AllergenicTree(
        "油松",
        "Pinus tabuliformis",
        599,
        1,
        2,
        11,
        95.03,
        13.4,
        "数量来自北京动物园乔木普查；其余参数借用颐和园同种数据",
    ),
    AllergenicTree(
        "毛白杨",
        "Populus tomentosa",
        314,
        2,
        2,
        20,
        94.99,
        17.8,
        "数量来自北京动物园乔木普查；其余参数借用颐和园同种数据",
    ),
)


PARKS = {
    "北京动物园": ParkProfile(
        name="北京动物园",
        total_area_ha=BEIJING_ZOO_TOTAL_AREA_HA,
        effective_green_area_ha=BEIJING_ZOO_EFFECTIVE_GREEN_AREA_HA,
        trees=BEIJING_ZOO_TREES,
        data_note=(
            "园区总面积按 86 ha；有效绿地按用户设定的 40 ha。"
            "乔木数量来自北京动物园乔木普查。"
        ),
        reliability_note=(
            "动物园目前只有树种数量是园区实测值；"
            "AP、PE、花期、冠幅和树高暂借用颐和园相同/近缘树种参数，"
            "因此 I_GZA 为代理估计。"
        ),
    ),
    "颐和园": ParkProfile(
        name="颐和园",
        total_area_ha=SUMMER_PALACE_TOTAL_AREA_HA,
        effective_green_area_ha=SUMMER_PALACE_EFFECTIVE_GREEN_AREA_HA,
        trees=SUMMER_PALACE_TREES,
        data_note=(
            "园区总面积 290.8 ha；有效绿地按整园 40% 计算，"
            f"即 {SUMMER_PALACE_EFFECTIVE_GREEN_AREA_HA:.2f} ha。"
        ),
        reliability_note=(
            "主要树种数量、AP、PE、花期、冠幅和树高均来自 "
            "Zhou et al. (2022) Table 4。"
        ),
    ),
}


# ============================================================
# 基础工具函数
# ============================================================

def clamp(value, minimum=0.0, maximum=100.0):
    return max(
        minimum,
        min(value, maximum)
    )


def gaussian_unit(
    value,
    optimal,
    sigma
):
    return math.exp(
        -((value - optimal) ** 2)
        / (2 * sigma ** 2)
    )


def logistic_unit(
    value,
    midpoint,
    steepness
):
    return 1.0 / (
        1.0
        + math.exp(
            -steepness
            * (value - midpoint)
        )
    )


def geometric_mean(values):
    positive_values = [
        max(float(v), 1e-6)
        for v in values
    ]

    log_mean = (
        sum(
            math.log(v)
            for v in positive_values
        )
        / len(positive_values)
    )

    return math.exp(log_mean)


# ============================================================
# I_GZA
#
# Zhou et al. (2022):
#
# I_GZA =
# [ Σ(N_i × AP_i × PE_i × FD_i × S_i × H_i) ]
# / (378 × S_T)
#
# N  = individual number
# AP = allergenic potential
# PE = pollen emission
# FD = flowering duration
# S  = crown projection area
# H  = canopy height
# ST = assessment-unit area (m²)
#
# canonical_igza:
#   严格按总园区面积作为 ST。
#
# effective_green_igza:
#   BJ Pollenix 扩展指标，把用户定义的“有效绿地面积”
#   作为局部植被源面积进行归一化。
#   它不是 Zhou et al. 原文的标准 I_GZA，故记作 I_GZA*。
# ============================================================

def igza_component(
    tree: AllergenicTree
):
    return (
        tree.count
        * tree.allergenic_potential
        * tree.pollen_emission
        * tree.flowering_duration
        * tree.crown_area
        * tree.canopy_height
    )


def calculate_igza(
    park: ParkProfile,
    area_ha: float
):
    numerator = sum(
        igza_component(tree)
        for tree in park.trees
    )

    area_m2 = (
        area_ha
        * 10000.0
    )

    return (
        numerator
        / (
            378.0
            * area_m2
        )
    )


def species_hazard_shares(
    park: ParkProfile
):
    raw = {
        tree.chinese_name:
        igza_component(tree)
        for tree in park.trees
    }

    total = max(
        sum(raw.values()),
        1e-9
    )

    return {
        name:
        100.0 * value / total
        for name, value in raw.items()
    }


# 颐和园有效绿地 I_GZA* 作为内部归一化参考。
SUMMER_PALACE_EFFECTIVE_IGZA = (
    calculate_igza(
        PARKS["颐和园"],
        PARKS["颐和园"].effective_green_area_ha
    )
)


def vegetation_score(
    effective_igza
):
    """
    以颐和园 I_GZA* 作为 100 分内部参考。
    这只是 BJ Pollenix 的跨公园相对比较尺度，
    不是医学概率或 Zhou et al. 的风险分界。
    """
    ratio = (
        effective_igza
        / max(
            SUMMER_PALACE_EFFECTIVE_IGZA,
            1e-9
        )
    )

    return clamp(
        ratio * 100.0
    )


# ============================================================
# 木本花粉浓度分级
#
# Zhou et al. (2022) Table 1:
# Woody pollen:
# Level 1 <= 100
# Level 2 101-250
# Level 3 251-400
# Level 4 401-800
# Level 5 > 800
# Unit: granule / 1000 mm²
#
# 这里把五个等级线性映射到 20/40/60/80/100，
# 仅用于 dashboard 的 0-100 内部显示。
# ============================================================

def woody_pollen_level(
    pollen_density
):
    if pollen_density <= 100:
        return 1
    elif pollen_density <= 250:
        return 2
    elif pollen_density <= 400:
        return 3
    elif pollen_density <= 800:
        return 4
    else:
        return 5


def pollen_score(
    pollen_density
):
    level = woody_pollen_level(
        pollen_density
    )

    return (
        level * 20.0
    )


# ============================================================
# 春季木本花粉季节因子
#
# 颐和园论文实证重点是春季 3-5 月。
# 为了让日期连续变化，用 4 月为中心做平滑 Gaussian。
#
# peak=4.0, sigma=0.85 是 BJ Pollenix 平滑参数，
# 不是 Zhou et al. 原论文回归系数。
# ============================================================

def circular_month_distance(
    month,
    peak_month
):
    diff = abs(
        month - peak_month
    )

    return min(
        diff,
        12 - diff
    )


def spring_season_factor(
    month
):
    distance = (
        circular_month_distance(
            month,
            4.0
        )
    )

    factor = (
        0.03
        + 0.97
        * math.exp(
            -(distance ** 2)
            / (
                2
                * 0.85 ** 2
            )
        )
    )

    return min(
        max(factor, 0.0),
        1.0
    )


# ============================================================
# 气象动态层
#
# 以下方向由北京花粉-气象研究支持：
# - 中等风速利于局地悬浮/传播，过大风速后局地浓度下降；
# - 春季约 5-20°C 更利于高花粉天气；
# - 降雨具有清除作用；
# - 湿度关系非线性；
# - 日照与花粉物候/释放相关。
#
# 具体 sigma / midpoint 是 BJ Pollenix 的平滑实现参数，
# 并非声称为临床阈值。
# ============================================================

def wind_condition_score(
    wind_speed
):
    return (
        100.0
        * gaussian_unit(
            wind_speed,
            optimal=3.0,
            sigma=1.6
        )
    )


def temperature_condition_score(
    temperature
):
    return (
        100.0
        * gaussian_unit(
            temperature,
            optimal=17.0,
            sigma=7.0
        )
    )


def humidity_condition_score(
    humidity
):
    return (
        100.0
        * gaussian_unit(
            humidity,
            optimal=55.0,
            sigma=20.0
        )
    )


def rainfall_condition_score(
    rainfall_48h
):
    # 降雨越多，空气中花粉越容易被清除。
    return (
        100.0
        * math.exp(
            -rainfall_48h
            / 12.0
        )
    )


def sunlight_condition_score(
    sunlight_hours
):
    return (
        100.0
        * logistic_unit(
            sunlight_hours,
            midpoint=6.0,
            steepness=0.35
        )
    )


def pm25_score(
    pm25
):
    return (
        100.0
        * logistic_unit(
            pm25,
            midpoint=75.0,
            steepness=0.03
        )
    )


# ============================================================
# 风险计算
#
# 结构：
# 1) 背景空气花粉等级 -> pollen score
# 2) I_GZA* -> local vegetation score
# 3) 日期 -> spring seasonal activation
# 4) 气象条件 -> weather score
# 5) PM2.5 -> experimental inflammatory modifier
#
# 为减少任意人工权重，天气内部采用几何平均，
# 暴露层采用背景花粉与季节性植被危险度的几何耦合。
#
# PM2.5 最大只提供约 10% 的实验性增强。
# 这仍是 BJ Pollenix 的模型设计，不是已发表临床公式。
# ============================================================

def calculate_risk(
    env: ParkEnvironment,
    park: ParkProfile
):
    date_obj = datetime.strptime(
        env.date,
        "%Y-%m-%d"
    )

    current_month = (
        date_obj.month
        + (date_obj.day - 1)
        / 30.0
    )

    canonical_igza = (
        calculate_igza(
            park,
            park.total_area_ha
        )
    )

    effective_igza = (
        calculate_igza(
            park,
            park.effective_green_area_ha
        )
    )

    V = vegetation_score(
        effective_igza
    )

    season = (
        spring_season_factor(
            current_month
        )
    )

    seasonal_V = (
        V
        * season
    )

    P = pollen_score(
        env.pollen_density
    )

    pollen_level = (
        woody_pollen_level(
            env.pollen_density
        )
    )

    W = wind_condition_score(
        env.wind_speed
    )

    T = temperature_condition_score(
        env.temperature
    )

    H = humidity_condition_score(
        env.humidity
    )

    R = rainfall_condition_score(
        env.rainfall_48h
    )

    S = sunlight_condition_score(
        env.sunlight_hours
    )

    M = pm25_score(
        env.pm25
    )

    weather_score = geometric_mean([
        W,
        T,
        H,
        R,
        S
    ])

    # 背景花粉是直接观测/输入的空气暴露；
    # 植被危险度是局部源强修正。
    exposure_score = geometric_mean([
        max(P, 1.0),
        max(seasonal_V, 1.0)
    ])

    # 天气只调制释放/传播条件，不直接制造花粉。
    base_risk = (
        exposure_score
        * (
            0.60
            + 0.40
            * weather_score
            / 100.0
        )
    )

    # 实验性 PM2.5 炎症增强，最大约 +10%。
    pm_multiplier = (
        1.0
        + 0.10
        * M
        / 100.0
    )

    total_risk = clamp(
        base_risk
        * pm_multiplier
    )

    if total_risk < 20:
        level = "低风险"
        recommendation = "一般可正常活动"
    elif total_risk < 40:
        level = "轻度风险"
        recommendation = "敏感人群可适当缩短户外停留"
    elif total_risk < 60:
        level = "中度风险"
        recommendation = "敏感人群建议减少长时间户外活动"
    elif total_risk < 80:
        level = "高风险"
        recommendation = "过敏人群建议佩戴口罩并减少停留"
    else:
        level = "极高风险"
        recommendation = "过敏人群建议尽量避免长时间进入园区"

    species_shares = (
        species_hazard_shares(
            park
        )
    )

    total_known_trees = sum(
        tree.count
        for tree in park.trees
    )

    tree_density = (
        total_known_trees
        / park.effective_green_area_ha
    )

    factors = {
        "木本花粉": P,
        "局部植被": seasonal_V,
        "风速条件": W,
        "温度条件": T,
        "湿度条件": H,
        "降雨条件": R,
        "日照条件": S,
        "PM2.5": M,
    }

    return {
        "风险评分": round(
            total_risk,
            2
        ),
        "风险等级": level,
        "活动建议": recommendation,
        "木本花粉等级": pollen_level,
        "木本花粉评分": round(
            P,
            2
        ),
        "标准 I_GZA": round(
            canonical_igza,
            4
        ),
        "有效绿地 I_GZA*": round(
            effective_igza,
            4
        ),
        "植被相对评分": round(
            V,
            2
        ),
        "春季活跃系数": round(
            season,
            3
        ),
        "季节性植被评分": round(
            seasonal_V,
            2
        ),
        "天气适宜度": round(
            weather_score,
            2
        ),
        "PM2.5增强系数": round(
            pm_multiplier,
            3
        ),
        "已纳入树木数量": total_known_trees,
        "有效绿地树木密度": round(
            tree_density,
            2
        ),
        "物种危险贡献": {
            k: round(v, 2)
            for k, v
            in species_shares.items()
        },
        "详细指标": {
            k: round(v, 2)
            for k, v
            in factors.items()
        },
    }


# ============================================================
# Streamlit UI
# ============================================================

st.set_page_config(
    page_title="京粉报",
    page_icon="🌿",
    layout="wide"
)

st.markdown("""
<style>

html, body, [class*="css"] {
    font-family: "Inter", "Noto Sans SC", sans-serif;
}

.block-container{
    padding-top: 2rem;
    padding-bottom: 2rem;
    max-width: 1220px;
}

h1{
    font-size: 2.1rem !important;
    font-weight: 700 !important;
    color: #183A37;
}

h2{
    font-size: 1.45rem !important;
    color: #183A37;
}

h3{
    font-size: 1.1rem !important;
    color: #183A37;
}

.small-en{
    color:#7B8A8B;
    font-size:0.78rem;
    margin-top:-5px;
    margin-bottom:12px;
}

[data-testid="stMetric"]{
    background: white;
    border-radius: 18px;
    padding: 18px;
    box-shadow: 0 3px 12px rgba(0,0,0,0.05);
    border: 1px solid #E7ECEF;
}

[data-testid="stMetricValue"]{
    color: #2D6A73;
}

section[data-testid="stSidebar"]{
    background-color: #F7FAFB;
    border-right: 1px solid #E4ECEE;
}

</style>
""", unsafe_allow_html=True)


st.markdown("""
<div style="
display:flex;
flex-direction:column;
align-items:center;
justify-content:center;
margin-top:4px;
margin-bottom:24px;
">

<div style="
font-size:68px;
font-weight:800;
line-height:1;
color:#2B2D42;
">
京粉报
</div>

<div style="
font-size:19px;
font-weight:500;
color:#6B7280;
margin-top:13px;
letter-spacing:0.5px;
">
BJ Pollenix
</div>

<div style="
font-size:13px;
color:#8A9496;
margin-top:7px;
">
Literature-grounded experimental pollen allergy risk index
</div>

</div>
""", unsafe_allow_html=True)


# ------------------------------------------------------------
# 公园切换：放在侧边栏最上面
# ------------------------------------------------------------

st.sidebar.markdown("""
## 公园数据
<div class='small-en'>
Park Dataset
</div>
""", unsafe_allow_html=True)

selected_park_name = st.sidebar.radio(
    "一键切换",
    options=[
        "北京动物园",
        "颐和园"
    ],
    horizontal=True,
    label_visibility="collapsed"
)

park = PARKS[
    selected_park_name
]

st.sidebar.success(
    f"当前：{park.name}"
)

st.sidebar.caption(
    park.data_note
)

st.sidebar.caption(
    f"有效绿地：{park.effective_green_area_ha:.2f} ha"
)

st.sidebar.caption(
    park.reliability_note
)

st.sidebar.divider()


# ------------------------------------------------------------
# 环境输入
# ------------------------------------------------------------

st.sidebar.markdown("""
## 环境参数
<div class='small-en'>
Environmental Parameters
</div>
""", unsafe_allow_html=True)


date = st.sidebar.date_input(
    "日期 / Date"
)


pollen_density = st.sidebar.slider(
    "木本花粉浓度（粒/1000 mm²）",
    min_value=0,
    max_value=1200,
    value=100,
    step=10
)


wind_speed = st.sidebar.slider(
    "风速 (m/s)",
    min_value=0.0,
    max_value=12.0,
    value=3.0,
    step=0.1
)


humidity = st.sidebar.slider(
    "湿度 (%)",
    min_value=0,
    max_value=100,
    value=55,
    step=1
)


rainfall_48h = st.sidebar.slider(
    "48h降雨量 (mm)",
    min_value=0.0,
    max_value=100.0,
    value=0.0,
    step=0.5
)


sunlight_hours = st.sidebar.slider(
    "日照时长 (h)",
    min_value=0.0,
    max_value=15.0,
    value=8.0,
    step=0.1
)


temperature = st.sidebar.slider(
    "温度 (°C)",
    min_value=-15.0,
    max_value=40.0,
    value=17.0,
    step=0.5
)


pm25 = st.sidebar.slider(
    "PM2.5 (μg/m³)",
    min_value=0,
    max_value=300,
    value=35,
    step=1
)


env = ParkEnvironment(
    date=str(date),
    pollen_density=pollen_density,
    wind_speed=wind_speed,
    humidity=humidity,
    rainfall_48h=rainfall_48h,
    sunlight_hours=sunlight_hours,
    temperature=temperature,
    pm25=pm25,
)


result = calculate_risk(
    env,
    park
)

risk = result[
    "风险评分"
]


# ------------------------------------------------------------
# 顶部指标
# ------------------------------------------------------------

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "当前公园",
        park.name
    )

with col2:
    st.metric(
        "综合风险评分",
        f"{risk}/100"
    )

with col3:
    st.metric(
        "风险等级",
        result["风险等级"]
    )

with col4:
    st.metric(
        "木本花粉等级",
        f"{result['木本花粉等级']} / 5"
    )


st.info(
    result[
        "活动建议"
    ]
)


# ------------------------------------------------------------
# 数据基础
# ------------------------------------------------------------

st.markdown("""
## 当前公园植被基础
<div class='small-en'>
Current Park Vegetation Dataset
</div>
""", unsafe_allow_html=True)


m1, m2, m3, m4 = st.columns(4)

with m1:
    st.metric(
        "总园区面积",
        f"{park.total_area_ha:.2f} ha"
    )

with m2:
    st.metric(
        "有效绿地",
        f"{park.effective_green_area_ha:.2f} ha"
    )

with m3:
    st.metric(
        "已纳入树木",
        f"{result['已纳入树木数量']} 株"
    )

with m4:
    st.metric(
        "有效绿地树木密度",
        f"{result['有效绿地树木密度']} 株/ha"
    )


# ------------------------------------------------------------
# 风险仪表盘 + I_GZA
# ------------------------------------------------------------

left, right = st.columns(
    [1, 1]
)

with left:

    st.markdown("""
    ### 综合风险仪表盘
    <div class='small-en'>
    Overall Risk Gauge
    </div>
    """, unsafe_allow_html=True)

    fig_gauge = go.Figure(
        go.Indicator(
            mode="gauge+number",
            value=risk,
            gauge={
                "axis": {
                    "range": [
                        0,
                        100
                    ]
                },
                "bar": {
                    "color": "#2D6A73"
                },
                "steps": [
                    {
                        "range": [0, 20],
                        "color": "#E8F4F2"
                    },
                    {
                        "range": [20, 40],
                        "color": "#D2E8E4"
                    },
                    {
                        "range": [40, 60],
                        "color": "#A9D0CA"
                    },
                    {
                        "range": [60, 80],
                        "color": "#73AAA3"
                    },
                    {
                        "range": [80, 100],
                        "color": "#3E7972"
                    }
                ]
            }
        )
    )

    fig_gauge.update_layout(
        height=300,
        margin=dict(
            l=20,
            r=20,
            t=30,
            b=10
        )
    )

    st.plotly_chart(
        fig_gauge,
        use_container_width=True
    )


with right:

    st.markdown("""
    ### 植被危险度
    <div class='small-en'>
    Vegetation Allergenicity
    </div>
    """, unsafe_allow_html=True)

    igza_df = pd.DataFrame({
        "指标": [
            "标准 I_GZA",
            "有效绿地 I_GZA*",
            "植被相对评分",
            "春季活跃系数"
        ],
        "数值": [
            result["标准 I_GZA"],
            result["有效绿地 I_GZA*"],
            result["植被相对评分"],
            result["春季活跃系数"]
        ]
    })

    st.dataframe(
        igza_df,
        use_container_width=True,
        hide_index=True
    )

    st.caption(
        "I_GZA 为文献指标；I_GZA* 是 BJ Pollenix "
        "按“有效绿地面积”重新归一化的跨公园比较指标。"
    )


# ------------------------------------------------------------
# 物种危险贡献
# ------------------------------------------------------------

st.markdown("""
## 主要过敏树种贡献
<div class='small-en'>
Allergenic Tree Hazard Contribution
</div>
""", unsafe_allow_html=True)


species_df = pd.DataFrame({
    "树种":
    list(
        result[
            "物种危险贡献"
        ].keys()
    ),
    "危险贡献 (%)":
    list(
        result[
            "物种危险贡献"
        ].values()
    )
})


fig_species = px.bar(
    species_df,
    x="树种",
    y="危险贡献 (%)",
    text="危险贡献 (%)",
    color="危险贡献 (%)",
    color_continuous_scale=[
        "#DCEFEB",
        "#2D6A73"
    ]
)

fig_species.update_layout(
    height=340,
    coloraxis_showscale=False,
    margin=dict(
        l=10,
        r=10,
        t=20,
        b=10
    )
)

fig_species.update_traces(
    textposition="outside"
)

st.plotly_chart(
    fig_species,
    use_container_width=True
)


# ------------------------------------------------------------
# 环境条件雷达图 + 指标
# ------------------------------------------------------------

left2, right2 = st.columns(
    [1, 1]
)

with left2:

    st.markdown("""
    ### 动态环境条件
    <div class='small-en'>
    Dynamic Environmental Conditions
    </div>
    """, unsafe_allow_html=True)

    detailed = result[
        "详细指标"
    ]

    radar_categories = list(
        detailed.keys()
    )

    radar_values = list(
        detailed.values()
    )

    radar_categories_closed = (
        radar_categories
        + [
            radar_categories[0]
        ]
    )

    radar_values_closed = (
        radar_values
        + [
            radar_values[0]
        ]
    )

    fig_radar = go.Figure()

    fig_radar.add_trace(
        go.Scatterpolar(
            r=radar_values_closed,
            theta=radar_categories_closed,
            fill="toself",
            line=dict(
                color="#2D6A73"
            ),
            fillcolor="rgba(45,106,115,0.30)"
        )
    )

    fig_radar.update_layout(
        polar=dict(
            radialaxis=dict(
                visible=True,
                range=[0, 100]
            )
        ),
        showlegend=False,
        height=360,
        margin=dict(
            l=30,
            r=30,
            t=30,
            b=20
        )
    )

    st.plotly_chart(
        fig_radar,
        use_container_width=True
    )


with right2:

    st.markdown("""
    ### 动态指标数据
    <div class='small-en'>
    Dynamic Indicator Values
    </div>
    """, unsafe_allow_html=True)

    detail_df = pd.DataFrame(
        result[
            "详细指标"
        ].items(),
        columns=[
            "指标",
            "评分"
        ]
    )

    st.dataframe(
        detail_df,
        use_container_width=True,
        hide_index=True
    )

    st.metric(
        "天气综合适宜度",
        result[
            "天气适宜度"
        ]
    )

    st.metric(
        "PM2.5增强系数",
        result[
            "PM2.5增强系数"
        ]
    )


# ------------------------------------------------------------
# 原始物种数据
# ------------------------------------------------------------

st.markdown("""
## 原始植被参数
<div class='small-en'>
Raw Vegetation Parameters
</div>
""", unsafe_allow_html=True)


raw_species_df = pd.DataFrame([
    {
        "树种":
            tree.chinese_name,
        "学名":
            tree.scientific_name,
        "株数":
            tree.count,
        "AP":
            tree.allergenic_potential,
        "PE":
            tree.pollen_emission,
        "花期(d)":
            tree.flowering_duration,
        "平均冠幅投影(m²)":
            tree.crown_area,
        "平均树高(m)":
            tree.canopy_height,
        "说明":
            tree.parameter_note,
    }
    for tree
    in park.trees
])

st.dataframe(
    raw_species_df,
    use_container_width=True,
    hide_index=True
)


# ------------------------------------------------------------
# 方法说明
# ------------------------------------------------------------

with st.expander(
    "模型方法与数据局限"
):

    st.markdown(
        r"""
### 1. 植被层

核心采用 Zhou et al. (2022) 使用的 **Green Zone Allergenicity Index (I_GZA)**：

\[
I_{GZA}
=
\\frac{
\\sum(
N_i AP_i PE_i FD_i S_i H_i
)
}{
378 S_T
}
\]

其中包括树木数量、致敏潜力、产粉能力、花期、冠幅和树高。

### 2. 有效绿地假设

本 App 另外计算 **I_GZA\***：

- 北京动物园有效绿地：**40 ha**
- 颐和园有效绿地：**290.8 × 40% = 116.32 ha**

这个 I_GZA* 是 BJ Pollenix 为比较局部有效绿地源强而加入的扩展，
不是 Zhou et al. 原论文定义。

### 3. 花粉浓度

木本花粉浓度分级直接采用 Zhou et al. (2022) Table 1 的五级标准，
单位为 **粒/1000 mm²**。

### 4. 气象层

风速、温度、湿度、降雨和日照用于动态修正。
这些变量的方向有北京花粉气象研究支持，
但本 App 中平滑曲线的具体 sigma / midpoint
仍属于模型实现参数，并非临床阈值。

### 5. 北京动物园局限

动物园目前拥有可靠的树种株数普查，
但没有获得与颐和园 Table 4 同维度的 AP/PE/FD/冠幅/树高数据库。
因此动物园使用颐和园同种或近缘树种参数作为 proxy。

### 6. 适用范围

这个版本主要针对 **春季木本花粉风险**。
旧版中 Artemisia 与 grass 的面积经验公式已移除，
因为目前没有两座公园可靠的草本普查数据。
"""
    )


st.caption(
    "BJ Pollenix is an experimental research/education index, "
    "not a medical diagnosis or official public-health warning system."
)